name: CI
on: push
jobs:
  test-job:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/checkout@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Install dependency
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm ci
      - name: list code
        run: |
          ls -a
          echo "Success"
      - name: unit test
        run: echo "npm run test"
  build-job:
    name: Build job
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/checkout@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Install dependency
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build code
        run: |
          npm run build
          ls -a
