name: CI
on: push
jobs:
  test-job:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: list code
        run: ls -a
      - run: echo "Good bye"
